apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  labels:
    argocd.argoproj.io/instance: podinfo-kargo-stages
  name: dev-podinfo
  namespace: podinfo
spec:
  promotionTemplate:
    spec:
      steps:
      - config:
          checkout:
          - branch: main
            path: ./src
          - branch: project/podinfo/component/dev-podinfo
            path: ./out
          repoURL: https://github.com/holos-run/kargo-demo.git
        uses: git-clone
      - config:
          path: ./out
        uses: git-clear
      - as: update-image
        config:
          images:
          - image: ghcr.io/stefanprodan/podinfo
          path: ./src/deploy/projects/podinfo/components/dev-podinfo
        uses: kustomize-set-image
      - config:
          outPath: ./out/dev-podinfo.gen.yaml
          path: ./src/deploy/projects/podinfo/components/dev-podinfo
        uses: kustomize-build
      - as: commit
        config:
          messageFromSteps:
          - update-image
          path: ./out
        uses: git-commit
      - config:
          path: ./out
          targetBranch: project/podinfo/component/dev-podinfo
        uses: git-push
      - config:
          apps:
          - name: podinfo-dev-podinfo
            sources:
            - desiredCommitFromStep: commit
              repoURL: https://github.com/holos-run/kargo-demo.git
        uses: argocd-update
  requestedFreight:
  - origin:
      kind: Warehouse
      name: podinfo
    sources:
      direct: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  labels:
    argocd.argoproj.io/instance: podinfo-kargo-stages
  name: prod-us-central-podinfo
  namespace: podinfo
spec:
  promotionTemplate:
    spec:
      steps:
      - config:
          checkout:
          - branch: main
            path: ./src
          - branch: project/podinfo/component/prod-us-central-podinfo
            path: ./out
          repoURL: https://github.com/holos-run/kargo-demo.git
        uses: git-clone
      - config:
          path: ./out
        uses: git-clear
      - as: update-image
        config:
          images:
          - image: ghcr.io/stefanprodan/podinfo
          path: ./src/deploy/projects/podinfo/components/prod-us-central-podinfo
        uses: kustomize-set-image
      - config:
          outPath: ./out/prod-us-central-podinfo.gen.yaml
          path: ./src/deploy/projects/podinfo/components/prod-us-central-podinfo
        uses: kustomize-build
      - as: commit
        config:
          messageFromSteps:
          - update-image
          path: ./out
        uses: git-commit
      - config:
          path: ./out
          targetBranch: project/podinfo/component/prod-us-central-podinfo
        uses: git-push
      - config:
          apps:
          - name: podinfo-prod-us-central-podinfo
            sources:
            - desiredCommitFromStep: commit
              repoURL: https://github.com/holos-run/kargo-demo.git
        uses: argocd-update
  requestedFreight:
  - origin:
      kind: Warehouse
      name: podinfo
    sources:
      stages:
      - uat
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  labels:
    argocd.argoproj.io/instance: podinfo-kargo-stages
  name: prod-us-east-podinfo
  namespace: podinfo
spec:
  promotionTemplate:
    spec:
      steps:
      - config:
          checkout:
          - branch: main
            path: ./src
          - branch: project/podinfo/component/prod-us-east-podinfo
            path: ./out
          repoURL: https://github.com/holos-run/kargo-demo.git
        uses: git-clone
      - config:
          path: ./out
        uses: git-clear
      - as: update-image
        config:
          images:
          - image: ghcr.io/stefanprodan/podinfo
          path: ./src/deploy/projects/podinfo/components/prod-us-east-podinfo
        uses: kustomize-set-image
      - config:
          outPath: ./out/prod-us-east-podinfo.gen.yaml
          path: ./src/deploy/projects/podinfo/components/prod-us-east-podinfo
        uses: kustomize-build
      - as: commit
        config:
          messageFromSteps:
          - update-image
          path: ./out
        uses: git-commit
      - config:
          path: ./out
          targetBranch: project/podinfo/component/prod-us-east-podinfo
        uses: git-push
      - config:
          apps:
          - name: podinfo-prod-us-east-podinfo
            sources:
            - desiredCommitFromStep: commit
              repoURL: https://github.com/holos-run/kargo-demo.git
        uses: argocd-update
  requestedFreight:
  - origin:
      kind: Warehouse
      name: podinfo
    sources:
      stages:
      - uat
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  labels:
    argocd.argoproj.io/instance: podinfo-kargo-stages
  name: prod-us-west-podinfo
  namespace: podinfo
spec:
  promotionTemplate:
    spec:
      steps:
      - config:
          checkout:
          - branch: main
            path: ./src
          - branch: project/podinfo/component/prod-us-west-podinfo
            path: ./out
          repoURL: https://github.com/holos-run/kargo-demo.git
        uses: git-clone
      - config:
          path: ./out
        uses: git-clear
      - as: update-image
        config:
          images:
          - image: ghcr.io/stefanprodan/podinfo
          path: ./src/deploy/projects/podinfo/components/prod-us-west-podinfo
        uses: kustomize-set-image
      - config:
          outPath: ./out/prod-us-west-podinfo.gen.yaml
          path: ./src/deploy/projects/podinfo/components/prod-us-west-podinfo
        uses: kustomize-build
      - as: commit
        config:
          messageFromSteps:
          - update-image
          path: ./out
        uses: git-commit
      - config:
          path: ./out
          targetBranch: project/podinfo/component/prod-us-west-podinfo
        uses: git-push
      - config:
          apps:
          - name: podinfo-prod-us-west-podinfo
            sources:
            - desiredCommitFromStep: commit
              repoURL: https://github.com/holos-run/kargo-demo.git
        uses: argocd-update
  requestedFreight:
  - origin:
      kind: Warehouse
      name: podinfo
    sources:
      stages:
      - uat
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  labels:
    argocd.argoproj.io/instance: podinfo-kargo-stages
  name: test-podinfo
  namespace: podinfo
spec:
  promotionTemplate:
    spec:
      steps:
      - config:
          checkout:
          - branch: main
            path: ./src
          - branch: project/podinfo/component/test-podinfo
            path: ./out
          repoURL: https://github.com/holos-run/kargo-demo.git
        uses: git-clone
      - config:
          path: ./out
        uses: git-clear
      - as: update-image
        config:
          images:
          - image: ghcr.io/stefanprodan/podinfo
          path: ./src/deploy/projects/podinfo/components/test-podinfo
        uses: kustomize-set-image
      - config:
          outPath: ./out/test-podinfo.gen.yaml
          path: ./src/deploy/projects/podinfo/components/test-podinfo
        uses: kustomize-build
      - as: commit
        config:
          messageFromSteps:
          - update-image
          path: ./out
        uses: git-commit
      - config:
          path: ./out
          targetBranch: project/podinfo/component/test-podinfo
        uses: git-push
      - config:
          apps:
          - name: podinfo-test-podinfo
            sources:
            - desiredCommitFromStep: commit
              repoURL: https://github.com/holos-run/kargo-demo.git
        uses: argocd-update
  requestedFreight:
  - origin:
      kind: Warehouse
      name: podinfo
    sources:
      stages:
      - dev
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  labels:
    argocd.argoproj.io/instance: podinfo-kargo-stages
  name: uat-podinfo
  namespace: podinfo
spec:
  promotionTemplate:
    spec:
      steps:
      - config:
          checkout:
          - branch: main
            path: ./src
          - branch: project/podinfo/component/uat-podinfo
            path: ./out
          repoURL: https://github.com/holos-run/kargo-demo.git
        uses: git-clone
      - config:
          path: ./out
        uses: git-clear
      - as: update-image
        config:
          images:
          - image: ghcr.io/stefanprodan/podinfo
          path: ./src/deploy/projects/podinfo/components/uat-podinfo
        uses: kustomize-set-image
      - config:
          outPath: ./out/uat-podinfo.gen.yaml
          path: ./src/deploy/projects/podinfo/components/uat-podinfo
        uses: kustomize-build
      - as: commit
        config:
          messageFromSteps:
          - update-image
          path: ./out
        uses: git-commit
      - config:
          path: ./out
          targetBranch: project/podinfo/component/uat-podinfo
        uses: git-push
      - config:
          apps:
          - name: podinfo-uat-podinfo
            sources:
            - desiredCommitFromStep: commit
              repoURL: https://github.com/holos-run/kargo-demo.git
        uses: argocd-update
  requestedFreight:
  - origin:
      kind: Warehouse
      name: podinfo
    sources:
      stages:
      - test
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  labels:
    argocd.argoproj.io/instance: podinfo-kargo-stages
  name: podinfo
  namespace: podinfo
spec:
  interval: 5m0s
  subscriptions:
  - image:
      discoveryLimit: 5
      repoURL: ghcr.io/stefanprodan/podinfo
      semverConstraint: ^6.0.0
      strictSemvers: true
