apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  labels:
    argocd.argoproj.io/instance: podinfo-kargo-project
  name: podinfo
spec:
  promotionPolicies:
  - autoPromotionEnabled: true
    stage: dev-podinfo
  - autoPromotionEnabled: true
    stage: test-podinfo
  - autoPromotionEnabled: true
    stage: uat-podinfo
