apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    annotations:
        kargo.akuity.io/authorized-stage: podinfo:prod-us-west-podinfo
    labels: {}
    name: podinfo-prod-us-west-podinfo
    namespace: argocd
spec:
    destination:
        server: https://kubernetes.default.svc
    project: podinfo
    source:
        path: deploy/projects/podinfo/components/prod-us-west-podinfo
        repoURL: https://github.com/holos-run/kargo-demo.git
        targetRevision: stage/prod-us-west
